(() => {
  const $ = selector => document.querySelector(selector);
  const state = { csrf: '', sources: [], items: [], editingSource: null, editingItem: null };
  const login = $('#adminLogin'); const app = $('#adminApp'); const notice = $('#adminNotice');
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[char]));
  const formData = form => Object.fromEntries(new FormData(form).entries());
  const say = (message, kind = '') => { if (notice) { notice.textContent = message; notice.dataset.kind = kind; } };
  async function request(path, options = {}) { const headers = { Accept: 'application/json', ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(state.csrf ? { 'X-Admin-CSRF': state.csrf } : {}), ...(options.headers || {}) }; const response = await fetch(path, { credentials: 'same-origin', ...options, headers }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || `Pedido falhou (${response.status})`); return payload; }
  function showApp() { login.hidden = true; app.hidden = false; }
  function showLogin(message = '') { login.hidden = false; app.hidden = true; $('#adminLoginStatus').textContent = message; }
  function resetSourceForm() { state.editingSource = null; const form = $('#sourceForm'); form.reset(); form.id.value = ''; form.enabled.checked = true; $('#sourceFormTitle').textContent = 'Nova fonte autorizada'; }
  function resetCatalogForm() { state.editingItem = null; const form = $('#catalogForm'); form.reset(); form.id.value = ''; $('#catalogFormTitle').textContent = 'Adicionar item'; }
  function fillSource(source) { state.editingSource = source; const form = $('#sourceForm'); form.id.value = source.id; form.name.value = source.name; form.kind.value = source.kind; form.baseUrl.value = source.baseUrl; form.allowedDomains.value = source.allowedDomains.join('\n'); form.description.value = source.description; form.enabled.checked = source.enabled; $('#sourceFormTitle').textContent = `Editar ${source.name}`; window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function fillCatalog(item) { state.editingItem = item; const form = $('#catalogForm'); form.id.value = item.id; form.sourceId.value = item.sourceId; form.contentType.value = item.contentType; form.title.value = item.title; form.description.value = item.description; form.externalUrl.value = item.externalUrl; form.mediaUrl.value = item.mediaUrl; form.thumbnailUrl.value = item.thumbnailUrl; form.streamType.value = item.streamType; form.feedName.value = item.feedName; form.country.value = item.country; form.language.value = item.language; form.categories.value = item.categories.join(', '); form.isLive.checked = item.isLive; form.isFeatured.checked = item.isFeatured; $('#catalogFormTitle').textContent = `Editar ${item.title}`; document.querySelector('[data-admin-tab="catalog"]').click(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function renderSources() { const box = $('#sourceList'); if (!state.sources.length) return box.innerHTML = '<div class="admin-empty">Ainda não existem fontes autorizadas.</div>'; box.innerHTML = state.sources.map(source => `<article class="admin-item"><div class="admin-item-main"><h3>${esc(source.name)}</h3><p>${esc(source.baseUrl)}</p><span class="admin-badge">${esc(source.kind)}</span><span class="admin-badge ${source.enabled ? 'online' : ''}">${source.enabled ? 'pública' : 'desativada'}</span><p>Allowlist: ${esc(source.allowedDomains.join(', '))}</p></div><div class="admin-item-actions"><button data-source-action="edit" data-id="${esc(source.id)}">Editar</button><button data-source-action="validate" data-id="${esc(source.id)}">Validar</button><button data-source-action="delete" data-id="${esc(source.id)}">Excluir</button></div></article>`).join(''); }
  function renderItem(item, approval = false) { const statusClass = item.approvalStatus === 'approved' ? 'online' : item.approvalStatus; const healthClass = item.healthStatus === 'online' ? 'online' : item.healthStatus === 'offline' || item.healthStatus === 'incompatible' ? 'offline' : ''; const actions = `<button data-item-action="edit" data-id="${esc(item.id)}">Editar</button><button data-item-action="validate" data-id="${esc(item.id)}">Validar</button>${item.approvalStatus !== 'approved' ? `<button data-item-action="approve" data-id="${esc(item.id)}">Aprovar</button>` : `<button data-item-action="reject" data-id="${esc(item.id)}">Retirar</button>`}<button data-item-action="delete" data-id="${esc(item.id)}">Excluir</button>`; return `<article class="admin-item"><div class="admin-item-main">${item.thumbnailUrl ? `<img src="${esc(item.thumbnailUrl)}" alt="" width="48" height="48" style="float:left;object-fit:cover;border-radius:8px;margin-right:10px">` : ''}<h3>${esc(item.title)}</h3><p>${esc(item.sourceName)} · ${esc(item.contentType)}${item.country ? ` · ${esc(item.country)}` : ''}</p><span class="admin-badge ${statusClass}">${esc(item.approvalStatus)}</span><span class="admin-badge ${healthClass}">${esc(item.healthLabel || item.healthStatus)}</span>${item.isFeatured ? '<span class="admin-badge">destaque</span>' : ''}<p>${esc(item.description).slice(0, 180)}</p></div><div class="admin-item-actions">${actions}</div></article>`; }
  function renderCatalog() { const box = $('#catalogList'); box.innerHTML = state.items.length ? state.items.map(item => renderItem(item)).join('') : '<div class="admin-empty">Nenhum item encontrado.</div>'; const approval = state.items.filter(item => item.approvalStatus === 'pending'); $('#approvalList').innerHTML = approval.length ? approval.map(item => renderItem(item, true)).join('') : '<div class="admin-empty">A fila de aprovação está vazia.</div>'; }
  async function loadOverview() { const data = await request('/api/admin/overview'); $('#metricSources').textContent = data.sources; $('#metricPending').textContent = data.pending; $('#metricApproved').textContent = data.approved; $('#metricOffline').textContent = data.offline; }
  async function loadSources() { const data = await request('/api/admin/sources'); state.sources = data.sources || []; $('#catalogSource').innerHTML = state.sources.map(source => `<option value="${esc(source.id)}">${esc(source.name)}</option>`).join('') || '<option value="">Cria uma fonte primeiro</option>'; renderSources(); }
  async function loadCatalog() { const params = new URLSearchParams(); if ($('#catalogStatus').value) params.set('status', $('#catalogStatus').value); if ($('#catalogType').value) params.set('type', $('#catalogType').value); const data = await request(`/api/admin/catalog?${params}`); state.items = data.items || []; renderCatalog(); }
  async function refresh() { try { await Promise.all([loadOverview(), loadSources(), loadCatalog()]); } catch (error) { say(error.message, 'error'); } }
  async function boot() { try { const session = await request('/api/admin/session'); if (!session.authenticated) return showLogin(session.configured ? '' : 'Admin ainda não configurado no ambiente do servidor.'); state.csrf = session.csrf; showApp(); await refresh(); } catch (error) { showLogin(error.message); } }
  $('#adminLoginForm').addEventListener('submit', async event => { event.preventDefault(); const status = $('#adminLoginStatus'); status.textContent = 'A autenticar…'; try { const data = await request('/api/admin/login', { method: 'POST', body: JSON.stringify(formData(event.currentTarget)) }); state.csrf = data.csrf; showApp(); await refresh(); } catch (error) { status.textContent = error.message; } });
  $('#adminLogout').addEventListener('click', async () => { try { await request('/api/admin/logout', { method: 'POST' }); state.csrf = ''; showLogin('Sessão terminada.'); } catch (error) { say(error.message, 'error'); } });
  document.querySelectorAll('[data-admin-tab]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-admin-tab]').forEach(item => item.classList.toggle('is-active', item === button)); document.querySelectorAll('[data-admin-panel]').forEach(panel => { panel.hidden = panel.dataset.adminPanel !== button.dataset.adminTab; }); }));
  $('#sourceReset').addEventListener('click', resetSourceForm); $('#catalogReset').addEventListener('click', resetCatalogForm); $('#refreshSources').addEventListener('click', loadSources); $('#refreshCatalog').addEventListener('click', loadCatalog); $('#refreshApproval').addEventListener('click', loadCatalog); $('#catalogStatus').addEventListener('change', loadCatalog); $('#catalogType').addEventListener('change', loadCatalog);
  $('#sourceForm').addEventListener('submit', async event => { event.preventDefault(); const data = formData(event.currentTarget); data.enabled = event.currentTarget.enabled.checked; data.allowedDomains = data.allowedDomains.split(/[,\n]/).map(value => value.trim()).filter(Boolean); try { const editing = Boolean(data.id); const path = editing ? `/api/admin/sources/${encodeURIComponent(data.id)}` : '/api/admin/sources'; delete data.id; await request(path, { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(data) }); say('Fonte guardada. Itens novos ficam pendentes de aprovação.', 'success'); resetSourceForm(); await refresh(); } catch (error) { say(error.message, 'error'); } });
  $('#catalogForm').addEventListener('submit', async event => { event.preventDefault(); const data = formData(event.currentTarget); data.categories = data.categories.split(',').map(value => value.trim()).filter(Boolean); data.isLive = event.currentTarget.isLive.checked; data.isFeatured = event.currentTarget.isFeatured.checked; const editing = Boolean(data.id); const path = editing ? `/api/admin/catalog/${encodeURIComponent(data.id)}` : '/api/admin/catalog'; delete data.id; try { await request(path, { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(data) }); say('Item guardado e enviado para aprovação.', 'success'); resetCatalogForm(); await refresh(); } catch (error) { say(error.message, 'error'); } });
  $('#sourceValidate').addEventListener('click', async () => { const form = $('#sourceForm'); if (!form.id.value) return say('Guarda a fonte antes de validar.', 'error'); try { const data = await request(`/api/admin/sources/${encodeURIComponent(form.id.value)}/validate`, { method: 'POST', body: JSON.stringify({}) }); say(`Fonte: ${data.validation.label}`, data.validation.status === 'online' ? 'success' : 'error'); } catch (error) { say(error.message, 'error'); } });
  $('#catalogValidate').addEventListener('click', async () => { const id = $('#catalogForm').id.value; if (!id) return say('Guarda o item antes de validar.', 'error'); try { const data = await request(`/api/admin/catalog/${encodeURIComponent(id)}/validate`, { method: 'POST' }); say(`Media: ${data.validation.label}`, data.validation.status === 'online' ? 'success' : 'error'); await refresh(); } catch (error) { say(error.message, 'error'); } });
  document.addEventListener('click', async event => { const sourceButton = event.target.closest('[data-source-action]'); const itemButton = event.target.closest('[data-item-action]'); try { if (sourceButton) { const source = state.sources.find(item => item.id === sourceButton.dataset.id); if (sourceButton.dataset.sourceAction === 'edit') fillSource(source); if (sourceButton.dataset.sourceAction === 'validate') { const data = await request(`/api/admin/sources/${encodeURIComponent(source.id)}/validate`, { method: 'POST', body: JSON.stringify({}) }); say(`Fonte: ${data.validation.label}`, data.validation.status === 'online' ? 'success' : 'error'); } if (sourceButton.dataset.sourceAction === 'delete' && confirm(`Excluir ${source.name} e os seus itens?`)) { await request(`/api/admin/sources/${encodeURIComponent(source.id)}`, { method: 'DELETE' }); await refresh(); } } if (itemButton) { const item = state.items.find(entry => entry.id === itemButton.dataset.id); const action = itemButton.dataset.itemAction; if (action === 'edit') fillCatalog(item); if (action === 'validate') { const data = await request(`/api/admin/catalog/${encodeURIComponent(item.id)}/validate`, { method: 'POST' }); say(`Media: ${data.validation.label}`, data.validation.status === 'online' ? 'success' : 'error'); await refresh(); } if (action === 'approve' || action === 'reject') { await request(`/api/admin/catalog/${encodeURIComponent(item.id)}/${action}`, { method: 'POST' }); await refresh(); } if (action === 'delete' && confirm(`Excluir ${item.title}?`)) { await request(`/api/admin/catalog/${encodeURIComponent(item.id)}`, { method: 'DELETE' }); await refresh(); } } } catch (error) { say(error.message, 'error'); } });
  boot();
})();
