(() => {
  const $ = selector => document.querySelector(selector);
  const state = { jobs: new Map(), sources: new Map(), pausedAll: false };
  const activeStatuses = new Set(['queued', 'fetching', 'downloading', 'paused']);
  const terminalStatuses = new Set(['completed', 'failed', 'cancelled']);
  const labels = { queued: 'Na fila', fetching: 'A analisar', downloading: 'A descarregar', paused: 'Pausado', completed: 'Concluído', failed: 'Falhou', cancelled: 'Cancelado' };
  function esc(value = '') { return String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
  function formatDate(value) { if (!value) return 'Agora'; try { return new Intl.DateTimeFormat('pt-PT', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value)); } catch { return 'Agora'; } }
  function progressOf(job) { return Math.max(0, Math.min(100, Number(job?.progress?.percent || 0))); }
  function activeJobs() { return [...state.jobs.values()].filter(job => activeStatuses.has(job.status)); }
  function renderSummary(payload = {}) { const counts = payload.counts || {}; $('#activeCount').textContent = String(payload.activeCount ?? activeJobs().length); $('#queuedCount').textContent = String(counts.queued || 0); $('#pausedCount').textContent = String(counts.paused || 0); $('#completedCount').textContent = String(counts.completed || 0); state.pausedAll = Boolean(payload.paused); $('#pauseAllButton').textContent = state.pausedAll ? 'Retomar tudo' : 'Pausar tudo'; }
  function renderList() { const container = $('#downloadsList'); const jobs = activeJobs(); $('#downloadsStatus').textContent = jobs.length ? `${jobs.length} ${jobs.length === 1 ? 'download ativo' : 'downloads ativos'}` : 'Nenhum download ativo neste momento.'; if (!jobs.length) { container.innerHTML = '<div class="u-empty">A fila está livre. Os ficheiros concluídos ficam disponíveis na Biblioteca.</div>'; return; } container.innerHTML = jobs.map(job => { const progress = progressOf(job); const paused = job.status === 'paused'; const status = job.error || job.progress?.label || labels[job.status] || job.status; return `<article class="download-live-card" data-download-id="${esc(job.id)}"><div class="download-live-thumb">${job.thumbnail ? `<img src="${esc(job.thumbnail)}" alt="" loading="lazy">` : '<span></span>'}</div><div class="download-live-main"><div class="download-live-title"><strong title="${esc(job.title)}">${esc(job.title || 'Download em preparação')}</strong><b>${Math.round(progress)}%</b></div><div class="download-live-meta"><span>${esc(job.formatLabel || job.format || 'Ficheiro')}</span><span>${esc(job.site || 'Fonte')}</span><span>${esc(status)}</span><span>${esc(formatDate(job.createdAt))}</span></div><div class="download-progress" aria-label="${Math.round(progress)}% concluído"><i style="width:${progress}%"></i></div></div><div class="download-live-actions"><button type="button" data-job-action="${esc(job.id)}">${paused ? 'Retomar' : 'Pausar'}</button><button class="danger" type="button" data-cancel-job="${esc(job.id)}">Cancelar</button></div></article>`; }).join(''); }
  function updateJob(job) { if (!job?.id) return; state.jobs.set(job.id, job); renderList(); const source = state.sources.get(job.id); if (terminalStatuses.has(job.status)) { window.setTimeout(() => { source?.close(); state.sources.delete(job.id); state.jobs.delete(job.id); renderList(); refresh(); }, 1500); } }
  function watchJob(job) { if (!job?.id || state.sources.has(job.id) || terminalStatuses.has(job.status)) return; const source = new EventSource(`/api/downloads/${encodeURIComponent(job.id)}/events`); state.sources.set(job.id, source); source.addEventListener('update', event => { try { updateJob(JSON.parse(event.data)); } catch {} }); source.onerror = () => { window.setTimeout(() => refresh(), 1600); }; }
  async function refresh() { try { const response = await fetch('/api/downloads', { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('Não foi possível consultar a fila.'); const payload = await response.json(); const activeIds = new Set((payload.jobs || []).map(job => job.id)); for (const id of state.jobs.keys()) if (!activeIds.has(id) && activeStatuses.has(state.jobs.get(id)?.status)) state.jobs.delete(id); (payload.jobs || []).forEach(job => { state.jobs.set(job.id, job); watchJob(job); }); renderSummary(payload); renderList(); $('#queueState').textContent = 'Online'; } catch (error) { $('#queueState').textContent = 'Indisponível'; $('#downloadsStatus').textContent = error.message || 'Não foi possível consultar a fila.'; } }
  async function action(url, method, success) { try { const response = await fetch(url, { method, headers: { Accept: 'application/json' } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || 'A operação falhou.'); await refresh(); if (success) $('#downloadsStatus').textContent = success; } catch (error) { $('#queueState').textContent = error.message || 'Operação indisponível'; } }
  $('#pauseAllButton')?.addEventListener('click', () => action(`/api/downloads/${state.pausedAll ? 'resume-all' : 'pause-all'}`, 'POST', state.pausedAll ? 'Downloads retomados.' : 'Downloads pausados.'));
  $('#downloadsList')?.addEventListener('click', event => { const pause = event.target.closest('[data-job-action]'); const cancel = event.target.closest('[data-cancel-job]'); if (pause) { const id = pause.dataset.jobAction; const job = state.jobs.get(id); action(`/api/downloads/${encodeURIComponent(id)}/${job?.status === 'paused' ? 'resume' : 'pause'}`, 'POST'); } if (cancel) action(`/api/downloads/${encodeURIComponent(cancel.dataset.cancelJob)}`, 'DELETE'); });
  refresh(); window.setInterval(refresh, 12000);
})();
