(() => {
  const $ = s => document.querySelector(s); const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  document.documentElement.dataset.theme = localStorage.getItem('tubematex-theme') || 'dark';
  const searchForm=$('#searchForm'), searchQuery=$('#searchQuery'), searchResults=$('#searchResults'), searchStatus=$('#searchStatus'), stage=$('#mediaStage'), video=$('#mediaVideo'), audio=$('#mediaAudio'), quickForm=$('#downloadForm'), quickUrl=$('#videoUrl'), quickFormat=$('#quickFormat'), quickQuality=$('#quickQuality'), queue=$('#liveQueue'); let current=null;
  const notify=(text,kind='')=>{searchStatus.textContent=text;searchStatus.dataset.kind=kind};
  const stop=()=>{[video,audio].forEach(media=>{if(media){media.pause();media.removeAttribute('src');media.load()}});video.hidden=false;audio.hidden=true;$('#playerContent').hidden=true;stage.hidden=true};
  const resultCard=item=>{const isAudio=item.kind==='music'||item.site==='SoundCloud'||item.site==='Spotify'||item.site==='Apple Music';const metadataOnly=Boolean(item.metadataOnly);return `<article class="h-result search-result" data-url="${esc(item.url)}" data-kind="${isAudio?'audio':'video'}" data-metadata-only="${metadataOnly}"><div class="h-thumb">${item.thumbnail?`<img src="${esc(item.thumbnail)}" alt="" loading="lazy">`:'<span></span>'}</div><div><strong>${esc(item.title||'Resultado sem título')}</strong><p>${esc(item.uploader||item.site||'Fonte pública')}${item.duration?` · ${Math.floor(item.duration/60)}:${String(Math.floor(item.duration%60)).padStart(2,'0')}`:''}${metadataOnly?' · catálogo':''}</p></div><div class="h-actions">${metadataOnly?`<a class="h-button primary" href="${esc(item.externalUrl||item.url)}" target="_blank" rel="noopener">Abrir fonte</a>`:`<button class="h-button preview" data-preview-url="${esc(item.url)}" data-preview-type="${isAudio?'audio':'video'}" type="button">${isAudio?'Ouvir':'Pré-visualizar'}</button><button class="h-button primary download" type="button">Baixar</button>`}</div></article>`};
  const render=items=>{searchResults.innerHTML=items.length?items.map(resultCard).join(''):'<div class="h-initial">Nenhum resultado encontrado. Tenta outro termo ou cola um URL público.</div>'};
  async function search(event){event.preventDefault();const q=searchQuery.value.trim();if(q.length<2)return notify('Indica pelo menos 2 caracteres para pesquisar.','error');notify('A pesquisar nas fontes configuradas…');searchResults.innerHTML='<div class="h-initial">A consultar resultados reais…</div>';try{const response=await fetch(`/api/search?q=${encodeURIComponent(q)}&type=all&source=all&limit=12`);const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'A pesquisa falhou.');render(payload.results||[]);notify(`${payload.results?.length||0} resultados reais encontrados.${payload.unavailableSources?.length?` Fontes indisponíveis: ${payload.unavailableSources.join(', ')}.`:''}`,'success')}catch(error){if(error.name==='AbortError')return;searchResults.innerHTML=(error.message.includes('429')||error.message.includes('rate limited'))?'<div class="h-initial rate-limit-card">Limite temporário atingido. Aguarda e tenta novamente.</div>':'<div class="h-initial">Não foi possível pesquisar agora.</div>';notify(error.message,'error')}}
  async function preview(item){stop();current=item;try{if(item.metadataOnly)return notify('Este item é metadata-only. Abre a fonte oficial para reproduzir.','error'); const response=await fetch(`/api/media/stream?url=${encodeURIComponent(item.url)}&type=${item.kind==='audio'?'audio':'video'}`);const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.url)throw new Error(payload.error||'Esta fonte não forneceu vídeo compatível.');$('#stageTitle').textContent=item.title;if(item.kind==='audio'){video.hidden=true;audio.hidden=false;audio.src=payload.url;audio.load();$('#playerContent').textContent='Contexto de áudio ativo — o vídeo permanece pausado.'}else{audio.hidden=true;video.hidden=false;video.src=payload.url;video.load();$('#playerContent').textContent='Contexto de vídeo ativo — o áudio permanece pausado.'}$('#playerContent').hidden=false;stage.hidden=false;notify(`${item.kind==='audio'?'Preview de áudio':'Preview de vídeo'} pronta.`,'success')}catch(error){notify(error.message,'error')}}
  async function download(url,format=quickFormat.value,quality=quickQuality.value){try{const response=await fetch('/api/downloads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,format,quality})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Não foi possível iniciar o download.');const job=payload.job||{};const item=document.createElement('div');item.className='h-queue-item';item.dataset.liveJob=job.id||'';item.innerHTML=`<strong>${esc(job.title||'Download')}</strong><span>Na fila · ${esc(format.toUpperCase())}</span>`;queue.prepend(item);notify('Download adicionado à fila.','success')}catch(error){notify(error.message,'error')}}
  searchForm.addEventListener('submit',search); $('#closeStage').addEventListener('click',stop); $('#downloadForm').addEventListener('submit',event=>{event.preventDefault();if(!quickUrl.value.trim())return notify('Cola um URL público para iniciar o download.','error');download(quickUrl.value.trim())}); searchResults.addEventListener('click',event=>{const card=event.target.closest('[data-url]');if(!card)return;const item={url:card.dataset.url,title:card.querySelector('strong')?.textContent||'Conteúdo',site:card.querySelector('p')?.textContent||'',kind:card.dataset.kind||'video',metadataOnly:card.dataset.metadataOnly==='true'};if(event.target.closest('.preview'))preview(item);if(event.target.closest('.download'))download(item.url,item.kind==='audio'?'mp3':'mp4','auto')});
  $('#searchResults').innerHTML='<div class="h-initial">A carregar vídeos e áudio reais das fontes configuradas…</div>'; fetch('/api/discover?area=home&limit=8').then(response=>response.ok?response.json():Promise.reject(new Error('Descoberta indisponível.'))).then(payload=>{render(payload.results||[]);notify(payload.results?.length?`Descoberta real · ${payload.results.length} itens.`:'Nenhuma fonte pública disponível agora.',payload.results?.length?'success':'')}).catch(()=>{searchResults.innerHTML='<div class="h-initial">Pesquisa para carregar resultados reais. Nenhuma fonte pública foi inventada.</div>'});
})();
