name: Node.js CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Imprimir diretório atual
      run: pwd

    - name: Listar estrutura de arquivos
      run: ls -la

    - name: Verificar estrutura do backend
      run: ls -la ./backend

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Verificar dependências do backend
      working-directory: './backend'
      run: |
        if [ ! -f "package-lock.json" ]; then
          echo "package-lock.json não encontrado. Instalando dependências..."
          npm install
        fi

    - name: Limpar cache do npm
      run: npm cache clean --force

    - name: Instalar dependências (backend)
      working-directory: './backend'
      run: npm ci || npm install

    - name: Build do projeto
      working-directory: './backend'
      run: npm run build --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Imprimir diretório atual
      run: pwd

    - name: Verificar estrutura do backend
      run: ls -la ./backend

    - name: Configurar Node.js (Deploy)
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Limpar cache do npm
      run: npm cache clean --force

    - name: Instalar dependências
      working-directory: './backend'
      run: npm ci || npm install

    - name: Iniciar servidor com PM2
      working-directory: './backend'
      run: |
        npm install pm2 -g
        pm2 start server.js --name "meu-servidor"
        pm2 save
        pm2 startup || true